export default {
  LOAD_PLANTS: 'LOAD_PLANTS',
  ADD_PLANT: 'ADD_PLANT',
  UPDATE_PLANT: 'UPDATE_PLANT',
  DELETE_PLANT: 'DELETE_PLANT',
  LOAD_PLANT: 'LOAD_PLANT',
  PLANTS_ERROR: 'PLANTS_ERROR',

  SIGNIN_USER: 'SIGNIN_USER',
  SIGNUP_USER: 'SIGNUP_USER',
  USER_ERROR: 'USER_ERROR',
};
